### ISSUE TITLE
Undefine WIN32_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/jsonpp#12]
That way other people's code doesn't break.

**Comment by Naav** [comment]
Unfortunately this doesn't prevent code breakage, because by the time the macro is undefined, `windows.h` has set its include guards and all future inclusions of it will therefore behave just as if the macro was still defined. I'm not sure how to fix this aside than purely not defining the macro in the first place.

**Comment by Rapptz** [comment]
Hopefully fixed. Just define `JSONPP_NO_macrohere`. e.g. `JSONPP_NO_WIN32_LEAN_AND_MEAN`.
