### ISSUE TITLE
Add a way to prettyprint json values.

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/jsonpp#5]
At the moment, `json::value` has a `to_string` member function that essentially gives a minimised JSON. That's good for some people, but there should be a way to get a properly "prettified" JSON.

**Comment by ThePhD** [comment]
on the `to_string` method, have a `json_string_flags` flag that allows users to customize how the printing is done. Recommendation is a 64-bit integer for the flag so that you can allocates bit 0 - 8 to indicate levels 1 to 8 spaces inbetween (which implies newlines) (this is how libjansson handles it). You may also want to consider potential uses for a flag that allows the user to "chop decimals" if they're whole number anyways.

If you don't have the flag approach, have a simple struct with a bunch of public, human-understandable members that customize the serialization (and give to_string a default one).

**Comment by Rapptz** [comment]
Fixed in 10f922c63c796c9d4422004d947cc3a0606f2278.
